=== sergutsan/migen-tawebtools/temp/test.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!-- common format describing input-data for analysis tools -->

<!-- general root-element for the document -->
<!ELEMENT interactiondata (preamble?, actions)>

<!ELEMENT preamble (users?, groups?, objects?, roles?, conditions?, document_information?, time_range?, description?, additional_information*)>

<!ELEMENT users (user_def*)>

<!ELEMENT user_def (description?)>
<!ATTLIST user_def id ID #REQUIRED>
<!ATTLIST user_def firstname CDATA #REQUIRED>
<!ATTLIST user_def lastname CDATA #IMPLIED>
<!ATTLIST user_def role CDATA #IMPLIED>

<!ELEMENT groups (group_def*)>

<!ELEMENT group_def (time_range?, description?)>
<!ATTLIST group_def id ID #REQUIRED>
<!ATTLIST group_def members CDATA #REQUIRED>

<!ELEMENT objects (object_def*)>

<!ELEMENT object_def (description?, properties?, additional_information*)>
<!ATTLIST object_def type CDATA #REQUIRED>
<!ATTLIST object_def id ID #REQUIRED>

<!ELEMENT roles (role_def*)>

<!ELEMENT role_def (description)>
<!ATTLIST role_def id ID #REQUIRED>

<!ELEMENT conditions (instructions?, description?)>
<!ATTLIST conditions creator_application CDATA #IMPLIED>
<!ATTLIST conditions application_version CDATA #IMPLIED>
<!ATTLIST conditions experimenter CDATA #IMPLIED>

<!ELEMENT instructions (instruction*)>

<!ELEMENT instruction (PCDATA)>
<!-- maybe some document-link, or some free text -->

<!ELEMENT time_range EMPTY>
<!ATTLIST time_range from CDATA #REQUIRED>
<!ATTLIST time_range to CDATA #REQUIRED>

<!-- root element for action-description -->
<!ELEMENT actions (action*)>

<!-- any action that is to be analyzed -->
<!ELEMENT action (actiontype, user+, object?, content?, transport?)>
<!ATTLIST action time CDATA #REQUIRED>

<!-- description of the action itself -->
<!-- classfication: a general classification, other for anything that does not fit into the classification, intendend for hand-edited actions, not for logged ones -->
<!-- type: more specific description, in case of logged actions the description used in the original environment -->
<!-- logged: describes if the action is autoimatically logged or hand-edited -->
<!ELEMENT actiontype (additional_information*)> 
<!ATTLIST actiontype classification (create | delete | read | write | move | modify | other) #REQUIRED>
<!ATTLIST actiontype type CDATA #REQUIRED>
<!ATTLIST actiontype logged (true | false) #REQUIRED>
<!ATTLIST actiontype succeed (true | false) #IMPLIED>

<!-- description of users involved into the action -->
<!-- role: at least one originator is to be given -->
<!ELEMENT user (additional_information*)>
<!ATTLIST user id CDATA #REQUIRED>
<!ATTLIST user ip CDATA #IMPLIED>
<!ATTLIST user role (originator | receiver) #REQUIRED> <!-- this reflects the role with respect to sending or receiving messages --> 
<!ATTLIST user user_role CDATA #IMPLIED> <!-- this reflects the role the user plays within the group, e.g. teacher, student, tutor, ...  -->

<!ELEMENT object (properties?, additional_information*)>
<!ATTLIST object id CDATA #REQUIRED>
<!ATTLIST object type CDATA #REQUIRED>

<!ELEMENT content (description?, properties?, additional_information*)>

<!ELEMENT properties (property*)>

<!ELEMENT property EMPTY>
<!ATTLIST property name CDATA #REQUIRED>
<!ATTLIST property value CDATA #REQUIRED>

<!ELEMENT transport ANY>
<!ATTLIST transport type CDATA #REQUIRED>

<!-- space for saving any kind of information wanted in the file, that is not covered anywhere else -->
<!ELEMENT additional_information ANY>
<!ATTLIST additional_information type CDATA #REQUIRED>

<!-- space for a human-readable description -->
<!ELEMENT description (#PCDATA)>

=== sergutsan/migen-tawebtools/temp/interaction - Copy.xml
<?xml version='1.0' ?>
<!DOCTYPE interactiondata SYSTEM "file://C:\Users\sokratis\Dropbox\Public\LKLProjects\temp\test.dtd">
<interactiondata>
	<preamble>
		<users>
			<user_def id="" firstname="" lastname="" role="">
				<description/>
			</user_def>
		</users>
		<groups>
			<group_def id="" members="">
				<time_range from="" to=""/>
				<description/>
			</group_def>
		</groups>
		<objects>
			<object_def type="" id="">
				<description/>
				<properties>
					<property name="" value=""/>
				</properties>
				<additional_information type=""/>
			</object_def>
		</objects>
		<roles>
			<role_def id="">
				<description/>
			</role_def>
		</roles>
		<conditions creator_application="" application_version="" experimenter="">
			<instructions>
				<instruction>
					<PCDATA/>
				</instruction>
			</instructions>
			<description/>
		</conditions>
		<document_information/>
		<time_range from="" to=""/>
		<description/>
		<additional_information type=""/>
	</preamble>
	<actions>
		<action time="">
			<actiontype classification="create" type="" logged="true" succeed="true">
				<additional_information type=""/>
			</actiontype>
			<user id="" ip="" role="originator" user_role="">
				<additional_information type=""/>
			</user>
			<object id="" type="">
				<properties>
					<property name="" value=""/>
				</properties>
				<additional_information type=""/>
			</object>
			<content>
				<description/>
				<properties>
					<property name="" value=""/>
				</properties>
				<additional_information type=""/>
			</content>
			<transport type=""/>
		</action>
	</actions>
</interactiondata>

=== sergutsan/migen-tawebtools/temp/test.xml
<?xml version='1.0' ?>
<!DOCTYPE actions SYSTEM "file://C:\Users\sokratis\Dropbox\Public\LKLProjects\temp\test.dtd">
<actions>
	<action time="">
		<actiontype classification="create" type="" logged="true" succeed="true">
			<additional_information type=""/>
		</actiontype>
		<user id="" ip="" role="originator" user_role="">
			<additional_information type=""/>
		</user>
		<object id="" type="">
			<properties>
				<property name="" value=""/>
			</properties>
			<additional_information type=""/>
		</object>
		<content>
			<description/>
			<properties>
				<property name="" value=""/>
			</properties>
			<additional_information type=""/>
		</content>
		<transport type=""/>
	</action>
</actions>
